### ISSUE TITLE
GPL legal / licensing information is not included in this repo, rootfs source code is missing

### ISSUE THREAD

**Issue by ArcadeHustle** [MiSTer-devel/Linux_Image_creator_MiSTer#12]
"The general rule is, if you distribute binaries, you must distribute the complete corresponding source code too." 
https://www.gnu.org/licenses/gpl-faq.html#UnchangedJustBinary

"Can I put the binaries on my Internet server and put the source on a different Internet site? 
Yes. Section 6(d) allows this. However, you must provide clear instructions people can follow to obtain the source, and you must take care to make sure that the source remains available for as long as you distribute the object code."
https://www.gnu.org/licenses/gpl-faq.html#SourceAndBinaryOnDifferentSites

"I want to distribute binaries, but distributing complete source is inconvenient. Is it ok if I give users the diffs from the “standard” version along with the binaries?
This is a well-meaning request, but this method of providing the source doesn't really do the job.

A user that wants the source a year from now may be unable to get the proper version from another site at that time. The standard distribution site may have a newer version, but the same diffs probably won't work with that version.

So you need to provide complete sources, not just diffs, with the binaries."
https://www.gnu.org/licenses/gpl-faq.html#DistributingSourceIsInconvenient

https://gpl-violations.org/about/
"Raise public awareness of the infringing use of free software, and thus putting pressure on the infringers."
![gplviolations3](https://user-images.githubusercontent.com/41961787/113164372-0ae6e180-920f-11eb-8da9-4348196e0d1d.png)

"What kind of source code do I have to publish under the GNU GPL?
The source code for a work means the preferred form of the work for making modifications to it. For an executable work, complete source code means all the source code for all modules it contains, plus any associated interface definition files, plus the scripts used to control compilation and installation of the executable."
https://gpl-violations.org/faq/sourcecode-faq/

"Complying with open source licenses"
https://buildroot.org/downloads/manual/manual.html#_complying_with_open_source_licenses

"Complying with the Buildroot license"
https://buildroot.org/downloads/manual/manual.html#legal-info-buildroot

https://busybox.net/shame.html
"Previously, this page listed products that included BusyBox but included neither source code nor offer for one. The BusyBox project has decided to not publicly shame companies until Conservancy has an opportunity to talk privately with companies who violate the GPL to convince them to comply with BusyBox's license."

<img width="439" alt="ExDfBUxXMAEAYG-" src="https://user-images.githubusercontent.com/41961787/113164777-6add8800-920f-11eb-8487-083358c217fc.png">

**Comment by ArcadeHustle** [comment]
@sorgelig  @Kitrinx please reference the Mr Fusion repo for how to properly comply with GPL. @michaelshmitty addressed this very quickly. I don't think it will be hard to do here either.  
https://github.com/MiSTer-devel/mr-fusion/commit/28bfc8877fb70ea7813d085614ef78ddea6a8786

**Comment by sorgelig** [comment]
Go to https://buildroot.org/download.html
download v2017.02 and build your own rootfs.

**Comment by ArcadeHustle** [comment]
That has nothing to do with your legal requirement to produce a proper license on this repo. You must at least do this. https://github.com/MiSTer-devel/Linux_Image_creator_MiSTer/pull/13

Secondarily, please go reread your requirements as an author under GPL: 
"Can I put the binaries on my Internet server and put the source on a different Internet site? 
Yes. Section 6(d) allows this. However, you must provide clear instructions people can follow to obtain the source, and you must take care to make sure that the source remains available for as long as you distribute the object code."
https://www.gnu.org/licenses/gpl-faq.html#SourceAndBinaryOnDifferentSites

**Comment by Kitrinx** [comment]
Why are you pinging me for a repo I clearly have no involvement with? Please stop harassing me in every different medium you can find.

**Comment by ArcadeHustle** [comment]
@Kitrinx you are a project spokesperson, both on Discord, and elsewhere. You know that, no one is harassing you, rather holding you accountable as a project spokesperson.
![Ew2C_joWUAAfefs](https://user-images.githubusercontent.com/41961787/113180496-ca8f5f80-921e-11eb-89bd-35644488485d.jpeg)
![Eww4USCWEAMG6lD](https://user-images.githubusercontent.com/41961787/113180542-d5e28b00-921e-11eb-83a1-021beccfacec.jpeg)

"a repo I clearly have no involvement with" oh spare us, you've been preaching on GPL on behalf of the MiSTER project for weeks now. This repo is linked under the main MiSter dev org that you participate in, your involvement is clear. I'm glad you are just now learning about GPL so that you can speak more authoritatively about it in the future. 
https://github.com/MiSTer-devel 
<img width="626" alt="image" src="https://user-images.githubusercontent.com/41961787/113180222-7e441f80-921e-11eb-90e5-553523bf51e5.png">

**Comment by Kitrinx** [comment]
Yes exactly, you were harassing me there too. The pre-scripted nature of your response is a good indication that you were ready to deliberately target me, after I said there I also have no involvement with this.

**Comment by ArcadeHustle** [comment]
@kitrinx if you want to play some sort of victim that is fine, your involvement in this project is not in question. Nor have YOUR own pre-scripted responses to defending GPL, which you clearly knew nothing about.

**Comment by ArcadeHustle** [comment]
None of the people behind the keys here are on MiSTer Discord just so you know. Nor have they directly interacted with you on ANY discord. Seems you are confused about your contrived harassment. If you don't want to speak on behalf of the project, and have users respond, stop acting as a PR person.

**Comment by ArcadeHustle** [comment]
@sorgelig Thank you for fixing the licensing as you were supposed to. It may be worth some effort educating the other devs on GPL licensing requirements, and unify your project message with regard to your responsibilities, and the rights of the users of the project given you chose GPL willingly.

**Comment by jotego** [comment]
I will remove the GPL3 license from my published works. I don't like its viral nature. It will take me a few days but I'll get rid of it.
