### ISSUE TITLE
Issue with dhcpcd / DNS record

### ISSUE THREAD

**Issue by ojaksch** [MiSTer-devel/Linux_Image_creator_MiSTer#15]
I'm running a well hung local DHCP/DNS setup, which is setting top-notch names in my local DNS zone. When rebooting the MiSTer, dhcpcd (the init script) doesn't release it's IP and DNS, so the DNS record is "already set" and the DNS server grumbles about this.

This is tolerable, but from time to time the DHCP server argues that "this IP address and DNS record is already in state and active", gives another IP and the DNS record ("forward map") fails. So no resolvable name and an unknown IP.

A proper fix would be easy by instructing dhcpcd to release it's settings just before shutting down the network interface:

```
--- S40network.org
+++ S40network
@@ -14,7 +14,9 @@
        ;;
   stop)
        printf "Stopping network: "
-       /sbin/ifdown -a
+       /usr/bin/umount -f -a -t cifs -t nfs4 -t nfs
+       /usr/sbin/dhcpcd -k
+       /sbin/ifdown -a --exclude=lo
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
   restart|reload)

```
  As you can see, in my case I'm unmounting all possible network ressources I'm using somethimes just to be sure. A shutdown of the network interface _without_ unmount leads to a hanging system when rebooting. If nothing is mounted, the unmount command keep quite and is doing nothing.

**Comment by sorgelig** [comment]
it's not so relevant as MiSTer doesn't use shutdown procedure. In most cases either power off or HW reset happens without chance to shutdown the network.

**Comment by ojaksch** [comment]
That is correct - in principle, but not when rebooting MiSTer, i.e. a forced reboot after update_all.sh ;)

**Comment by sorgelig** [comment]
script may include this unmounting as it's related only to that script. All these lines can be called blindly without knowing if it was mounted or started.
