### ISSUE TITLE
firmware.tar.gz Feature Request - Add firmware file for bluetooth Asus BT400

### ISSUE THREAD

**Issue by Klezstyle** [MiSTer-devel/Linux_Image_creator_MiSTer#16]
Hi,

I´d like to propose adding the required firmware file "BCM20702A1-0b05-17cb.hcd" to firmware.tar.gz.

This file is required for the bluetooth dongle Asus BT400, which uses a Broadcom chip.

Link to file (35 Kb):
https://github.com/winterheart/broadcom-bt-firmware/blob/master/brcm/BCM20702A1-0b05-17cb.hcd

This single firmware file must be installed as:  /lib/firmware/brcm/BCM20702A1-0b05-17cb.hcd
Permissions: root:root 0644

Now the Mister linux kernel 5.15.1 works with my dongle:
[    2.940494] Bluetooth: hci0: BCM: chip id 63
[    2.942818] Bluetooth: hci0: BCM: features 0x07
[    2.974503] Bluetooth: hci0: BCM20702A
[    2.974525] Bluetooth: hci0: BCM20702A1 (001.002.014) build 0000
[    2.982737] Bluetooth: hci0: BCM20702A1 'brcm/BCM20702A1-0b05-17cb.hcd' Patch
[    3.898513] Bluetooth: hci0: Broadcom Bluetooth Device
[    3.898538] Bluetooth: hci0: BCM20702A1 (001.002.014) build 1467

I´m happily using this Asus BT400 dongle with a Sony Dual Shock 4 via bluetooth.

Thanks

**Comment by sorgelig** [comment]
added
