### ISSUE TITLE
Create symlink /usr/local -> /media/fat/linux/local

### ISSUE THREAD

**Issue by wesclemens** [MiSTer-devel/Linux_Image_creator_MiSTer#2]
Since the Linux root partition is updated as one package and any manual changes are clobbered when an update is necessary.  I would like to suggest that a symlink be created for /usr/local to /media/fat/linux/local. This would allow for local changes to the Linux distributions to be maintained on the SD card under linux/local and not be clobbered with root partition updates.

My use case for this change is I have a WiFi adapter that requires firmware not packaged with MiSTer. I could and currently do store my firmware under linux/local/lib/firmware. I feel that this solution is more approachable for people that need to add custom firmware or other unique changes.

If you agree this change is acceptable, I would be happy to create a pull request. I'm guessing it would be added to the addon.tar?

**Comment by wesclemens** [comment]
I guess an additional symlink is need to make Linux search for firmware in /usr/local.

I tried setting 'firmware_class.path' in U-Boot but that didn't seem to work.

A patch could always be applied to the kernel itself. [here](https://github.com/MiSTer-devel/Linux-Kernel_MiSTer/blob/fb1c592cf4c9eeb84ec6bce13c13c11c7d05b6c7/drivers/base/firmware_loader/main.c#L279-L285)

But the simplest solution is to just add a few links.
ln -s /media/fat/linux/local /usr/local
ln -s /usr/local/lib/firmware /lib/firmware/updates

**Comment by sorgelig** [comment]
i will think about it. I don't want to complicate the things. Linux on MiSTer doesn't expect customizations as it's not PC.
Actually Linux release is not so frequent. You can simply copy your firmware to original place. Or make PR for firmwares.tar.gz  and it will be included into next release.

**Comment by wesclemens** [comment]
I understand your desire to keep things simple. I have created a pull request to add the firmware.
