### ISSUE TITLE
btpair fix for more than one pairing device

### ISSUE THREAD

**Issue by bootsector** [MiSTer-devel/Linux_Image_creator_MiSTer#6]
If there's more than one device in pairing mode, btpair script fails with something like:

`/sbin/btpair: line 8: [: E4:17:D8:FF:FF:FF: binary operator expected`

I suggest changing line 7 from btpair script from:

`MAC=$(hcitool scan --flush | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}')`

to:

`MAC=$(hcitool scan --flush | grep -o -m 1 -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}')`

So only the first match will be captured.

**Comment by sorgelig** [comment]
thanks!
i will add it.

**Comment by sorgelig** [comment]
added
