### ISSUE TITLE
HPS only assigned 512 MB out of available 1GB DDR3 ram?

### ISSUE THREAD

**Issue by michaelshmitty** [MiSTer-devel/Linux_Image_creator_MiSTer#8]
Apparently you can configure how much of the 1GB DDR3 ram is assigned to the Linux OS on the DE10-nano. I know it can be shared with the fpga. Has the 512 been explicitly configured for MiSTer or is that just the default setting?

Is it safe to make the full 1GB available to the hps or wil that create problems for the fpga to use the ram?

Thanks.

**Comment by michaelshmitty** [comment]
I was looking in the wrong place. Of course this stuff is in the u-boot_MiSTer repository. I found the exact location where the 512 gets set:
https://github.com/MiSTer-devel/u-boot_MiSTer/commit/ef0d403310dcf73df1966f1d2bf8a91db1aff6af#diff-27ec1d4e3b85e2b9c21524fd257f8c57R22

So I was just curious what the reason is for splitting the RAM. Is it because some cores also use the DDR3 ram (I'm no fgpa expert). Thanks!

**Comment by sorgelig** [comment]
512MB is for HPS and 512MB for FPGA.
It was discussed many times. Please use forum for discussion. It's not an issue.
