### ISSUE TITLE
Which version of libusb is included?  (re: issues with xow user-mode driver)

### ISSUE THREAD

**Issue by sofakng** [MiSTer-devel/Linux_Image_creator_MiSTer#9]
I'm trying to the 'xow' (Xbox Wireless Adapter) user-mode driver to work and if I recompile libusb-1.0.23 it appears to work, but if I link the included libusb-1.0.so it doesn't.

Which exact version/subversion of libusb is included in MiSTer?

**Comment by sorgelig** [comment]
it's 1.0.20
what adapter your are talking about? If XBox360 wireless adapter then it works fine already IIRC.

**Comment by sofakng** [comment]
Thanks!

I'm talking about the [Xbox One Wireless Adapter](https://www.xbox.com/en-US/accessories/adapters/wireless-adapter-windows).  The newer Xbox One controllers support bluetooth so this isn't a high priority issue.  However, the Xbox One controllers support a [proprietary 5 GHz signal](https://gist.github.com/devkid/4b3bd50760504d1b93ea684cfd3ed895) that is supposed to have much lower latency than bluetooth.

There is a project called [xow](https://github.com/medusalix/xow) that implements a user-mode driver to support this wireless adapter.

I've been able to successfully cross-compile and run this driver on the latest MiSTer linux version, but I had to recompile libusb and I'm not sure why yet.

**Comment by sorgelig** [comment]
try to compile the project against libusb 1.0.20
may be some structures are different.

**Comment by sofakng** [comment]
Will do.  Thanks very much!

**Comment by sorgelig** [comment]
probably you can compile with exact linkage to libusb-1.0.23.so then can include this lib along with driver so it will co-exist with 1.0.20 (as 1.0.so). I'm not sure if 2 versions of lubusb can co-exist.

**Comment by sofakng** [comment]
I'm in a bit over my head, but what I did was cross-compile libusb-1.0.23 and then linked using 'rpath' option so when I ran the executable, it looked for libusb in the same directory as itself instead of using the system library (/lib) directory.

Is that what you meant?

**Comment by sorgelig** [comment]
if it works then fine.

**Comment by sofakng** [comment]
Sorry -- One more question... what version of systemd (libudev) is MiSTer using?

libusb optionally requires libudev as well for device enumeration/hotplug support.

**Comment by sorgelig** [comment]
MiSTer uses eudev 3.2.1
